# Generated by Django 4.2.5 on 2023-09-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trialapp', '0002_tag_projects_vote_ratio_projects_vote_total_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
