# Generated by Django 4.1.1 on 2023-10-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trialapp', '0003_alter_tag_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
