# Generated by Django 4.1.1 on 2023-10-02 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trialapp', '0004_alter_projects_created_alter_review_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='feature_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
    ]
